name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change si ta branche principale s'appelle autrement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'  # Le dossier de ton site ('.' = racine)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
